### ISSUE TITLE
Stake Management Page

### ISSUE THREAD

**Issue by JayChrawnna** [TheKusamarian/stake-n-vote#15]
- Unbond
- Add Stake
- change reward destination
- nominator list with stats

"Perhaps this is part of the staking management upgrade but today, if I go to the staking section with an account that is partially staked (let's say 1000 staked and 1000 free) i am forced to only delegate.

There could be a button that requests to "Stake More" or "Delegate voting power"

**Comment by niklasp** [comment]
How do we name buttons?

I suggest we also add 2 buttons:
- stake more
- remove stake

then user can select how much they want to add / remove, do you agree to the naming? "Stake More" + "Remove Stake"?

**Comment by JayChrawnna** [comment]
Perfect!
