### ISSUE TITLE
og-image for social media sharing

### ISSUE THREAD

**Issue by niklasp** [TheKusamarian/stake-n-vote#29]
1200 x 630

@JayChrawnna can you ping someone to create a social media image that appears when e.g. sharing thekus.xyz on discord / telegram / twitter

below wagmedia example

![Uploading Bildschirmfoto 2024-07-01 um 14.59.48.png…]()

**Comment by JayChrawnna** [comment]
Can we just use the "Get your assets to work" page in these dimensions?

**Comment by niklasp** [comment]
you mean, screenshot that section in the dimensions?

**Comment by JayChrawnna** [comment]
yeeeeup
