### ISSUE TITLE
 Improve Delegation Process

### ISSUE THREAD

**Issue by niklasp** [TheKusamarian/stake-n-vote#6]
- [ ] Max delegation amount is calculated correctly based on users votes / delegation status, ...
- [ ] Show tracks user is currently delegating to / delegation status (e.g. You are already delegating your votes on the following tracks: ...

**Comment by UsmanLiaqat404** [comment]
Hy @niklasp

**Comment by UsmanLiaqat404** [comment]
i want to contribute need more information
